"""Create Role model

Revision ID: 8f57d4683d58
Revises: 540bd16c442f
Create Date: 2023-11-07 15:50:06.543933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f57d4683d58'
down_revision = '540bd16c442f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
