"""Create Role model

Revision ID: 96f8cea98685
Revises: 8f57d4683d58
Create Date: 2023-11-07 15:50:59.771552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f8cea98685'
down_revision = '8f57d4683d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Role', sa.Column('ezgi', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Role', 'ezgi')
    # ### end Alembic commands ###
