"""Create Role model

Revision ID: ef31dc45f1bd
Revises: 7aee40d27816
Create Date: 2023-11-07 16:36:54.654941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef31dc45f1bd'
down_revision = '7aee40d27816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Role', sa.Column('ezgi', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Role', 'ezgi')
    # ### end Alembic commands ###
