from sqlalchemy import Column, ForeignKey
from sqlalchemy.types import String, DateTime, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class ArkAccessPrivileges(Base):
    __tablename__ = 'ArkAccessPrivileges'
    _id = Column(String, primary_key=True)

    api_server_controller_create = Column(Boolean),
    api_server_controller_delete = Column(Boolean),
    api_server_controller_update = Column(Boolean),
    api_server_controller_view = Column(Boolean),
    archived_software_list_of_device_create = Column(Boolean),
    archived_software_list_of_device_delete = Column(Boolean),
    archived_software_list_of_device_update = Column(Boolean),
    archived_software_list_of_device_view = Column(Boolean),
    authorized_technical_service_create = Column(Boolean),
    authorized_technical_service_definition_create = Column(Boolean),
    authorized_technical_service_definition_delete = Column(Boolean),
    authorized_technical_service_definition_update = Column(Boolean),
    authorized_technical_service_definition_view = Column(Boolean),
    authorized_technical_service_delete = Column(Boolean),
    authorized_technical_service_update = Column(Boolean),
    authorized_technical_service_view = Column(Boolean),
    communication_parameter_page_create = Column(Boolean),
    communication_parameter_page_delete = Column(Boolean),
    communication_parameter_page_update = Column(Boolean),
    communication_parameter_page_view = Column(Boolean),
    default_gib_comm_param_create = Column(Boolean),
    default_gib_comm_param_delete = Column(Boolean),
    default_gib_comm_param_update = Column(Boolean),
    default_gib_comm_param_view = Column(Boolean),
    default_gib_parameter_page_create = Column(Boolean),
    default_gib_parameter_page_delete = Column(Boolean),
    default_gib_parameter_page_update = Column(Boolean),
    default_gib_parameter_page_view = Column(Boolean),
    default_parameter_definition_create = Column(Boolean),
    default_parameter_definition_delete = Column(Boolean),
    default_parameter_definition_update = Column(Boolean),
    default_parameter_definition_view = Column(Boolean),
    define_product_groups_create = Column(Boolean),
    define_product_groups_delete = Column(Boolean),
    define_product_groups_update = Column(Boolean),
    define_product_groups_view = Column(Boolean),
    device_definition_page_create = Column(Boolean),
    device_definition_page_delete = Column(Boolean),
    device_definition_page_update = Column(Boolean),
    device_definition_page_view = Column(Boolean),
    device_definition_with_financial_number_create = Column(Boolean),
    device_definition_with_financial_number_delete = Column(Boolean),
    device_definition_with_financial_number_update = Column(Boolean),
    device_definition_with_financial_number_view = Column(Boolean),
    device_list_create = Column(Boolean),
    device_list_delete = Column(Boolean),
    device_list_update = Column(Boolean),
    device_list_view = Column(Boolean),
    exchange_rate_create = Column(Boolean),
    exchange_rate_delete = Column(Boolean),
    exchange_rate_update = Column(Boolean),
    exchange_rate_view = Column(Boolean),
    general_software_list_create = Column(Boolean),
    general_software_list_delete = Column(Boolean),
    general_software_list_update = Column(Boolean),
    general_software_list_view = Column(Boolean),
    gib_parameter_page_create = Column(Boolean),
    gib_parameter_page_delete = Column(Boolean),
    gib_parameter_page_update = Column(Boolean),
    gib_parameter_page_view = Column(Boolean),
    job_file_upload_create = Column(Boolean),
    job_file_upload_delete = Column(Boolean),
    job_file_upload_update = Column(Boolean),
    job_file_upload_view = Column(Boolean),
    main_product_getter_create = Column(Boolean),
    main_product_getter_delete = Column(Boolean),
    main_product_getter_update = Column(Boolean),
    main_product_getter_view = Column(Boolean),
    merchant_definition_create = Column(Boolean),
    merchant_definition_delete = Column(Boolean),
    merchant_definition_update = Column(Boolean),
    merchant_definition_view = Column(Boolean),
    merchant_edit_create = Column(Boolean),
    merchant_edit_delete = Column(Boolean),
    merchant_edit_update = Column(Boolean),
    merchant_edit_view = Column(Boolean),
    merchant_file_list_create = Column(Boolean),
    merchant_file_list_delete = Column(Boolean),
    merchant_file_list_update = Column(Boolean),
    merchant_file_list_view = Column(Boolean),
    merchant_list_create = Column(Boolean),
    merchant_list_delete = Column(Boolean),
    merchant_list_update = Column(Boolean),
    merchant_list_view = Column(Boolean),
    merchant_sale_file_wizard_create = Column(Boolean),
    merchant_sale_file_wizard_delete = Column(Boolean),
    merchant_sale_file_wizard_update = Column(Boolean),
    merchant_sale_file_wizard_view = Column(Boolean),
    merchant_sale_upload_create = Column(Boolean),
    merchant_sale_upload_delete = Column(Boolean),
    merchant_sale_upload_update = Column(Boolean),
    merchant_sale_upload_view = Column(Boolean),
    merchant_sale_wizard_create = Column(Boolean),
    merchant_sale_wizard_delete = Column(Boolean),
    merchant_sale_wizard_update = Column(Boolean),
    merchant_sale_wizard_view = Column(Boolean),
    okc_certificate_information_create = Column(Boolean),
    okc_certificate_information_delete = Column(Boolean),
    okc_certificate_information_update = Column(Boolean),
    okc_certificate_information_view = Column(Boolean),
    okc_integration_registry_create = Column(Boolean),
    okc_integration_registry_delete = Column(Boolean),
    okc_integration_registry_update = Column(Boolean),
    okc_integration_registry_view = Column(Boolean),
    okc_integration_situation_create = Column(Boolean),
    okc_integration_situation_delete = Column(Boolean),
    okc_integration_situation_update = Column(Boolean),
    okc_integration_situation_view = Column(Boolean),
    pos_device_definition_create = Column(Boolean),
    pos_device_definition_delete = Column(Boolean),
    pos_device_definition_update = Column(Boolean),
    pos_device_definition_view = Column(Boolean),
    pos_device_list_create = Column(Boolean),
    pos_device_list_delete = Column(Boolean),
    pos_device_list_update = Column(Boolean),
    pos_device_list_view = Column(Boolean),
    pos_device_user_create = Column(Boolean),
    pos_device_user_delete = Column(Boolean),
    pos_device_user_update = Column(Boolean),
    pos_device_user_view = Column(Boolean),
    pos_device_wizard_create = Column(Boolean),
    pos_device_wizard_delete = Column(Boolean),
    pos_device_wizard_update = Column(Boolean),
    pos_device_wizard_view = Column(Boolean),
    pos_user_wizard_create = Column(Boolean),
    pos_user_wizard_delete = Column(Boolean),
    pos_user_wizard_update = Column(Boolean),
    pos_user_wizard_view = Column(Boolean),
    produced_devices_definition_create = Column(Boolean),
    produced_devices_definition_delete = Column(Boolean),
    produced_devices_definition_update = Column(Boolean),
    produced_devices_definition_view = Column(Boolean),
    produced_devices_list_create = Column(Boolean),
    produced_devices_list_delete = Column(Boolean),
    produced_devices_list_update = Column(Boolean),
    produced_devices_list_view = Column(Boolean),
    product_groups_company_list_create = Column(Boolean),
    product_groups_company_list_delete = Column(Boolean),
    product_groups_company_list_update = Column(Boolean),
    product_groups_company_list_view = Column(Boolean),
    profile_definition_page_create = Column(Boolean),
    profile_definition_page_delete = Column(Boolean),
    profile_definition_page_update = Column(Boolean),
    profile_definition_page_view = Column(Boolean),
    profile_edit_page_create = Column(Boolean),
    profile_edit_page_delete = Column(Boolean),
    profile_edit_page_update = Column(Boolean),
    profile_edit_page_view = Column(Boolean),
    profile_list_page_create = Column(Boolean),
    profile_list_page_delete = Column(Boolean),
    profile_list_page_update = Column(Boolean),
    profile_list_page_view = Column(Boolean),
    profile_sale_wizard_create = Column(Boolean),
    profile_sale_wizard_delete = Column(Boolean),
    profile_sale_wizard_update = Column(Boolean),
    profile_sale_wizard_view = Column(Boolean),
    profiled_software_list_create = Column(Boolean),
    profiled_software_list_delete = Column(Boolean),
    profiled_software_list_update = Column(Boolean),
    profiled_software_list_view = Column(Boolean),
    role_authorization_create = Column(Boolean),
    role_authorization_delete = Column(Boolean),
    role_authorization_edit_page_create = Column(Boolean),
    role_authorization_edit_page_delete = Column(Boolean),
    role_authorization_edit_page_update = Column(Boolean),
    role_authorization_edit_page_view = Column(Boolean),
    role_authorization_update = Column(Boolean),
    role_authorization_view = Column(Boolean),
    role_list_create = Column(Boolean),
    role_list_delete = Column(Boolean),
    role_list_update = Column(Boolean),
    role_list_view = Column(Boolean),
    service_controller_create = Column(Boolean),
    service_controller_delete = Column(Boolean),
    service_controller_update = Column(Boolean),
    service_controller_view = Column(Boolean),
    software_definition_from_profile_create = Column(Boolean),
    software_definition_from_profile_delete = Column(Boolean),
    software_definition_from_profile_update = Column(Boolean),
    software_definition_from_profile_view = Column(Boolean),
    software_list_of_device_create = Column(Boolean),
    software_list_of_device_delete = Column(Boolean),
    software_list_of_device_update = Column(Boolean),
    software_list_of_device_view = Column(Boolean),
    software_upload_page_create = Column(Boolean),
    software_upload_page_delete = Column(Boolean),
    software_upload_page_update = Column(Boolean),
    software_upload_page_view = Column(Boolean),
    terminal_definition_page_create = Column(Boolean),
    terminal_definition_page_delete = Column(Boolean),
    terminal_definition_page_update = Column(Boolean),
    terminal_definition_page_view = Column(Boolean),
    terminal_edit_page_create = Column(Boolean),
    terminal_edit_page_delete = Column(Boolean),
    terminal_edit_page_update = Column(Boolean),
    terminal_edit_page_view = Column(Boolean),
    terminal_list_page_create = Column(Boolean),
    terminal_list_page_delete = Column(Boolean),
    terminal_list_page_update = Column(Boolean),
    terminal_list_page_view = Column(Boolean),
    terminal_sale_wizard_create = Column(Boolean),
    terminal_sale_wizard_delete = Column(Boolean),
    terminal_sale_wizard_update = Column(Boolean),
    terminal_sale_wizard_view = Column(Boolean),
    user_access_privileges_name = Column(String),
    user_definition_create = Column(Boolean),
    user_definition_delete = Column(Boolean),
    user_definition_update = Column(Boolean),
    user_definition_view = Column(Boolean),
    user_list_create = Column(Boolean),
    user_list_delete = Column(Boolean),
    user_list_update = Column(Boolean),
    user_list_view = Column(Boolean)

    created_date = Column(DateTime)

    # role_id = Column(ForeignKey(Role.id))  # Role ile ilişkilendirme
    # admins = relationship(Role, backref=Admins)

    @staticmethod
    def save_db(engine, data):
        try:
            Base.metadata.create_all(engine, checkfirst=Column(Boolean))
            Session = sessionmaker(bind=engine)
            session = Session()
            for i in data:
                my_model = AccessPrivileges(**i)
                session.add(my_model)
                session.commit()
        except Exception as ex:
            print("EXXXXXXXXXX", ex)
